# Generated by Django 2.1.8 on 2019-04-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=64)),
                ('numeric', models.IntegerField(null=True)),
                ('alphanumeric', models.CharField(max_length=256, null=True)),
            ],
            options={
                'db_table': 'demo__definition',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.IntegerField(blank=True, null=True)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('link_type', models.IntegerField(blank=True, null=True)),
                ('link_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'demo__link',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_on', models.DateTimeField(blank=True, null=True)),
                ('saved_by', models.CharField(blank=True, max_length=256, null=True)),
                ('first_name', models.CharField(blank=True, max_length=256, null=True)),
                ('last_name', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'demo_person',
            },
        ),
        migrations.CreateModel(
            name='PersonAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_on', models.DateTimeField(blank=True, null=True)),
                ('saved_by', models.CharField(blank=True, max_length=256, null=True)),
                ('person_id', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=256, null=True)),
                ('last_name', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'demo_person_audit',
            },
        ),
    ]
